version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/var/lib/mysql/
    networks:
      work-net:
        ipv4_address: 172.20.2.11
  adminer:
    image: adminer
    restart: always
    networks:
      work-net:
        ipv4_address: 172.20.2.12
    ports:
      - "8081:8080"
  php:
    build: ./docker-php
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      work-net:
        ipv4_address: 172.20.2.13

  web:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    links:
      - php
    networks:
      work-net:
        ipv4_address: 172.20.2.14

networks:
  work-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/25